### ISSUE TITLE
Awesome-Salim-quotes

### ISSUE THREAD

**Issue by lovemyselfworld** [narze/awesome-salim-quotes#61]
เชื่อไม่เหมือนกันก็เรื่องนึงนะ แต่ไม่มีตรรกะไม่ยึดหลักกฏหมาย พร้อมจะบิดข้อมูลและกล้าเอาข่าวปั่นมาทำลายคนที่ตัวเองเกลียดโดยไม่สนว่าความจริงคืออะไร ถามจริง ไม่นึกละอายตัวเองบ้างเหรอคะ?

**Comment by narze** [comment]
thanks!
